### ISSUE TITLE
Error in ''make''

### ISSUE THREAD

**Issue by pcampolina** [carolinabigonha/br-atlas#7]
Hello, i'm receiving this error when i try to run "make". Npm and the others packets installed with no issues. Any info about this? Thanks

/br-atlas$ make
mkdir -p zip/
curl 'ftp://geoftp.ibge.gov.br/malhas_digitais/municipio_2010/ac/ac_municipios.zip' -o zip/ac-municipalities.zip.download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (9) Server denied you to change to the given directory
make: **\* [zip/ac-municipalities.zip] Error 9

**Comment by diegopenhanut** [comment]
Hello.
There is no `malhas_digitais` dir inside `ftp://geoftp.ibge.gov.br/`. Probably your url is wrong.

**Comment by pcampolina** [comment]
Hello! Thanks for the fast answer.

I just followed the usage mentioned:

sudo apt-get install gdal-bin
git clone https://github.com/carolinabigonha/br-atlas.git
cd br-atlas
npm install
make

You are right! This dir doesn't realy exist. How can i change the command to skip this file? I may be wrong but this dir seems to be only a small part of the "return of make command". Thanks

**Comment by pcampolina** [comment]
Actually, i just want Brazil's regions (only a map with the big 5). I dont need much haha.

**Comment by diegopenhanut** [comment]
I did a pull request. You can wait it to be accepted or clone my fork  if you are in a hurry. https://github.com/diegopenhanut/br-atlas/

**Comment by diegopenhanut** [comment]
@pcampolina I did a pull request. You can wait it to be accepted or clone my fork if you are in a hurry. https://github.com/diegopenhanut/br-atlas/

**Comment by pcampolina** [comment]
Thanks alot! I'm going to try it :)

**Comment by marpontes** [comment]
Hey, @diegopenhanut I've just submitted a PR #9 right before I saw yours - sorry, my bad.

However, mine points to the 2016 files. IDK the differences but anyone feel free to check it out in [my fork](https://github.com/marpontes/br-atlas/) and let's give @carolinabigonha the right to choose.

cheers 🍻

**Comment by diegopenhanut** [comment]
Hi @marpontes! No problem. Did you try to generate a Brazil map with all municipalities? It seems it only gets the first municipalities for each state. It seems the problem is https://github.com/carolinabigonha/br-atlas/blob/master/scripts/merge.py, but my python is quite rusty. Do you have any clue?

**Comment by carolinabigonha** [comment]
Thank you @navarrovmn, @marpontes and @diegopenhanut for the contribution on the FTP url error. I am sorry for taking so long to merge the pull requests. Since they are all the same fix, I have accepted the most recent (@navarrovmn) and I will add all three of you in the contributors list.
